name: CI

# triggers on
on: [push]

jobs:
  test:
    env:
      RAILS_ENV: test
      NODE_ENV: test
    runs-on: ubuntu-latest # runner
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout repository # copies repo in runner
        uses: actions/checkout@v2 # short for https://github.com/actions/checkout
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1 # short for https://github.com/ruby/setup-ruby
        with:
          ruby-version: 3.1.2
          # runs 'bundle install' and caches installed gems automatically
          bundler-cache: true
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "20.5.1"
      - name: Get Yarn cache directory path
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Setup cache key and directory for node_modules cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: Yarn install & bundle install
        run: |
          cd escapades_backend
          yarn install --frozen-lockfile
          bundle install
          cd ..
          cd escapades_frontend
          yarn install --frozen-lockfile
      - name: Prepare DB
        run: |
          cd escapades_backend
          cp config/database.github.yml config/database.yml
          bundle exec rails db:create db:migrate
        # if we use rspec tags (js, flaky, quarantine)
      - name: Run RSpec tests
        run: |
          cd escapades_backend
          bundle exec rspec -f d --tag ~js --tag ~flaky --tag ~quarantine
      - name: Run RSpec JS tests
        run: |
          cd escapades_backend
          bundle exec rspec -f d --tag js --tag ~flaky --tag ~quarantine
      - name: Run RSpec flaky tests
        run: |
          cd escapades_backend
          bundle exec rspec -f d --tag flaky
        continue-on-error: true
      - name: Run RSpec quarantine tests
        run: |
          cd escapades_backend
          bundle exec rspec -f d --tag quarantine
        continue-on-error: true
      - name: Run Vitest tests
        run: cd escapades_frontend && yarn test
